# To be worked on...

[[packages]]
name = "test"
version = "1.0.0"
authors = ["Jesse"]
url = "https://teamoctaneforever.github.io/pkgs/test.txt"

[[packages]]
name = "bigtest"
version = "1.0.0"
authors = ["Jesse"]
url = "https://teamoctaneforever.github.io/pkgs/megabyte.txt"

[[packages]]
name = "multi-test"
version = "1.0.0"
authors = ["Jesse"]
url = ["https://teamoctaneforever.github.io/pkgs/placeholder.txt", "https://teamoctaneforever.github.io/pkgs/test.txt"]
