# To be worked on...

[repository]
name = "main"


[[packages]]
name = "test"
version = "1.0.0"
authors = ["Jesse"]
url = "https://teamoctaneforever.github.io/pkgs/test.txt"
license = "OPK Open-Source"
format = "txt"

[[packages]]
name = "bigtest"
version = "1.0.0"
authors = ["Jesse"]
url = "https://teamoctaneforever.github.io/pkgs/megabyte.txt"
license = "OPK Open-Source"
format = "txt"
