# To be worked on...

[[packages]]
name = "test"
version = "1.0.0"
authors = ["Jesse"]
url = "https://teamoctaneforever.github.io/pkgs/test.txt"

[[packages]]
name = "bigtest"
version = "1.0.0"
authors = ["Jesse"]
url = "https://teamoctaneforever.github.io/pkgs/20megabyte.txt"
